[package]
name = "minskk-dict"
version = "0.1.0"
edition = "2021"

[lib]
name = "minskk"
crate-type = ["cdylib"]

[dependencies]
dirs = "5.0.1"
encoding_rs = "0.8.34"
libc = "0.2.0"
once_cell = "1.19.0"
shellexpand = "3.1.0"

